version: "3.7"

services:
  postgres:
    image: postgres
    container_name: fullstackjr_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fullstackjr-database
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: fullstackjr_app
    build: .
    environment:
      DB_HOST: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres:
